CREATE TABLE graph (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE vertex (
    id BIGSERIAL PRIMARY KEY,
    graph_id BIGINT REFERENCES graph (id) ON DELETE CASCADE,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL
);

CREATE TABLE edge (
    id BIGSERIAL PRIMARY KEY,
    graph_id BIGINT REFERENCES graph (id) ON DELETE CASCADE,
    "from" BIGINT NOT NULL REFERENCES vertex (id) ON DELETE CASCADE,
    "to" BIGINT NOT NULL REFERENCES vertex (id) ON DELETE CASCADE,
    weight FLOAT NOT NULL
);